# Generated by Django 3.1.6 on 2021-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('DateOfJoin', models.DateField()),
            ],
        ),
    ]
