# Generated by Django 3.1.6 on 2021-03-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
